image: archlinux
packages:
  - jdk11-openjdk
  - podman
sources:
  - https://git.sr.ht/~xaffe/takingstack
  - https://git.sr.ht/~tcarrio/github-sync
  - https://git.sr.ht/~tcarrio/git-mirror
environment:
  PROJECT_DIR: github-sync
  GIT_TARGET_REPO: git@github.com:tcarrio/github-sync.git
secrets:
  - 4e983fc2-9d24-43eb-9986-1c18feb2e7b8
tasks:
  - start-db: sudo podman run --rm -it -d --name=pgsql -e POSTGRES_PASSWORD=localdev -e POSTGRES_DB=sync_db -p 5432:5432 postgres
  - test: |
      sudo archlinux-java set java-11-openjdk
      cd $PROJECT_DIR
      ./mvnw clean test
  - stop-db: sudo podman stop pgsql
  - mirror-all: git-mirror/git-mirror.sh $PROJECT_DIR